#!/bin/bash
source ${OPENSHIFT_HOMEDIR}/python/virtenv/bin/activate
cd $OPENSHIFT_REPO_DIR
echo "Executing 'python manage.py makemigratations'"
python manage.py makemigrations
echo "Executing 'python manage.py syncdb'"
python manage.py syncdb
echo "Executing 'python manage.py createcachetable'"
python manage.py createcachetable
echo "Executing 'python manage.py collectstatic --noinput'"
python manage.py collectstatic --noinput
